### ISSUE TITLE
KONTAKT iBeacon - Major and Minor are incorrect

### ISSUE THREAD

**Issue by ghost** [liamnichols/iBeaconScanner#1]
With KONTAKT iBeacon (http://kontakt.io) Major and Minor does not always correctly recognised. When Major or Minor is incorrect, the app displays negative value.

 Real Major: 
41264
 Displayed Major:
 -24272

Note: 
 1. Correct Major/Minor can be viewer either from values printed on iBeacon's box or via Apple's AirLocate demo app.
 2. The HiBeacons app however always correctly detect characteristics of iPhone 5 configured as an iBeacon (via AirLocate).

**Comment by liamnichols** [comment]
I was incorrectly casting the major and minor values as `int16_t` (signed) and not `uint16_t` (unsigned). 
All Major/Minor values should now be correctly read.

There is also a new build (1.0.1) that has these changes applied

Thanks,
Liam
