### ISSUE TITLE
KONTAKT iBeacon - only one iBeacon is discovered

### ISSUE THREAD

**Issue by ghost** [liamnichols/iBeaconScanner#2]
When two KONTAKT iBeacons (http://kontakt.io) are near, the iBeacon Scanner discovers only one of them. The choice what iBeacon to discover does not change between trials. 

Note: 
1. Both iBeacons are ranging by Apple's AirLocate demo app.
2. Both iBeacons have the same Proximity UUID, but different Major/Minor combinations

**Comment by liamnichols** [comment]
Please could you check out the latest version and see if you can identify both beacons now.

Thanks

**Comment by ghost** [comment]
It works as expected!
I would suggest to rename UUID -> Proximity UUID as it is how Apple calls it.

Thanks.
